x-image: &image strafrecht:dev
x-entrypoint: &entrypoint python manage.py

services:

  storage:
    image: postgres:13
    ports:
      - 5432:5432
    env_file:
      - backend.env
    command: postgres -c 'max_connections=400'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U django" ]
      interval: 1s
      timeout: 1s
      retries: 30

#  init:
#    image: *image
#    depends_on:
#      storage:
#        condition: service_healthy
#    env_file:
#      - backend.env
#      - ../.env
#    entrypoint: *entrypoint
#    command: migrate

  backend: &backend
    build:
      context: ..
      dockerfile: Dockerfile
#    build: ../Dockerfile
#      Dockerfile:
#      context: ..
#      image: *image
    depends_on:
      storage:
        condition: service_healthy
    entrypoint: python
    ports:
      - 8000:8000
    env_file:
      - backend.env
      - ../.env
    # NOTE: Do not set entrypoint as this image will become incompatible with PyCharm Remote Debugger
    command: manage.py runserver 0.0.0.0:8000
